"""llm calls

Revision ID: ef0dd52c0214
Revises: 5bc8e929de42
Create Date: 2026-10-08 09:52:40.729908

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Unset settings become NULL instead of raising, so a missing context matches no rows.
CURRENT_WORKSPACE = "NULLIF(current_setting('app.workspace_id', true), '')::uuid"

# revision identifiers, used by Alembic.
revision: str = 'ef0dd52c0214'
down_revision: str | None = '5bc8e929de42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'error')", name=op.f('ck_llm_calls_status')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_llm_calls_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_workspace_id_created_at', 'llm_calls', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Row-level security: rows are visible and writable only in the current workspace.
    op.execute("ALTER TABLE llm_calls ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE llm_calls FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY llm_calls_isolation ON llm_calls
            FOR ALL
            USING (workspace_id = {CURRENT_WORKSPACE})
            WITH CHECK (workspace_id = {CURRENT_WORKSPACE})
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS llm_calls_isolation ON llm_calls")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_calls_workspace_id_created_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###