"""tickets and mock orders

Revision ID: c4071fd14902
Revises: 27bee49d7cf7
Create Date: 2026-10-08 14:18:34.038618

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Unset settings become NULL instead of raising, so a missing context matches no rows.
CURRENT_WORKSPACE = "NULLIF(current_setting('app.workspace_id', true), '')::uuid"
TENANT_TABLES = ("tickets", "mock_orders")

# revision identifiers, used by Alembic.
revision: str = 'c4071fd14902'
down_revision: str | None = '27bee49d7cf7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_orders',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'shipped', 'delivered', 'cancelled')", name=op.f('ck_mock_orders_status')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mock_orders_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mock_orders')),
    sa.UniqueConstraint('workspace_id', 'order_number', name=op.f('uq_mock_orders_workspace_id'))
    )
    op.create_table('tickets',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name=op.f('ck_tickets_priority')),
    sa.CheckConstraint("source IN ('widget', 'manual')", name=op.f('ck_tickets_source')),
    sa.CheckConstraint("status IN ('new', 'triaged', 'awaiting_review', 'replied', 'resolved')", name=op.f('ck_tickets_status')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tickets_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_tickets_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_tickets_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tickets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index('ix_tickets_workspace_id_created_at', 'tickets', ['workspace_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_tickets_workspace_id_status', 'tickets', ['workspace_id', 'status'], unique=False)
    op.add_column('conversations', sa.Column('ticket_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_conversations_ticket_id_tickets'), 'conversations', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('messages', sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('route', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###

    op.create_check_constraint(
        op.f("ck_messages_route"),
        "messages",
        "route IN ('answer', 'fallback', 'small_talk', 'handoff')",
    )

    # Row-level security: rows are visible and writable only in the current workspace.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_isolation ON {table}
                FOR ALL
                USING (workspace_id = {CURRENT_WORKSPACE})
                WITH CHECK (workspace_id = {CURRENT_WORKSPACE})
            """
        )


def downgrade() -> None:
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_isolation ON {table}")
    op.drop_constraint(op.f("ck_messages_route"), "messages", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'route')
    op.drop_column('messages', 'classification')
    op.drop_constraint(op.f('fk_conversations_ticket_id_tickets'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'ticket_id')
    op.drop_index('ix_tickets_workspace_id_status', table_name='tickets')
    op.drop_index('ix_tickets_workspace_id_created_at', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('mock_orders')
    # ### end Alembic commands ###