"""widget chat

Revision ID: 27bee49d7cf7
Revises: ef0dd52c0214
Create Date: 2026-10-08 12:09:36.181538

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Unset settings become NULL instead of raising, so a missing context matches no rows.
CURRENT_WORKSPACE = "NULLIF(current_setting('app.workspace_id', true), '')::uuid"
TENANT_TABLES = ("contacts", "conversations", "messages", "feedback")

# revision identifiers, used by Alembic.
revision: str = '27bee49d7cf7'
down_revision: str | None = 'ef0dd52c0214'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('anonymous_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contacts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('workspace_id', 'anonymous_id', name=op.f('uq_contacts_workspace_id'))
    )
    op.create_table('conversations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('widget')", name=op.f('ck_conversations_channel')),
    sa.CheckConstraint("status IN ('open', 'needs_human', 'closed')", name=op.f('ck_conversations_status')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversations_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_workspace_id_last_message_at', 'conversations', ['workspace_id', 'last_message_at', 'id'], unique=False)
    op.create_table('messages',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'assistant', 'agent', 'system')", name=op.f('ck_messages_role')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], name=op.f('fk_messages_llm_call_id_llm_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_messages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_workspace_id_conversation_id_created_at', 'messages', ['workspace_id', 'conversation_id', 'created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating IN ('up', 'down')", name=op.f('ck_feedback_rating')),
    sa.CheckConstraint("source IN ('customer')", name=op.f('ck_feedback_source')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_feedback_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_feedback_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('message_id', name=op.f('uq_feedback_message_id'))
    )
    op.create_index('ix_feedback_workspace_id_created_at', 'feedback', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Row-level security: rows are visible and writable only in the current workspace.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_isolation ON {table}
                FOR ALL
                USING (workspace_id = {CURRENT_WORKSPACE})
                WITH CHECK (workspace_id = {CURRENT_WORKSPACE})
            """
        )

    # Widget key lookup before any tenant context exists. The function runs as its owner
    # (this migration's role), and FORCE RLS applies to the owner too, so the owner gets a
    # read-only policy on workspaces. The app role is unaffected: it can only reach this
    # through the function, which returns nothing but the id and allowed origins.
    op.execute(
        """
        DO $$
        BEGIN
            EXECUTE format(
                'CREATE POLICY workspaces_widget_key_lookup ON workspaces FOR SELECT TO %I USING (true)',
                current_user
            );
        END
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION resolve_widget_key(key text)
        RETURNS TABLE (workspace_id uuid, allowed_origins text[])
        LANGUAGE sql
        STABLE
        SECURITY DEFINER
        SET search_path = pg_catalog, pg_temp
        AS $$
            SELECT w.id, w.allowed_origins
            FROM public.workspaces AS w
            WHERE w.widget_public_key = key
        $$
        """
    )
    op.execute("REVOKE ALL ON FUNCTION resolve_widget_key(text) FROM PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION resolve_widget_key(text) TO resolveai_app")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS resolve_widget_key(text)")
    op.execute("DROP POLICY IF EXISTS workspaces_widget_key_lookup ON workspaces")
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_workspace_id_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_messages_workspace_id_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_workspace_id_last_message_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('contacts')
    # ### end Alembic commands ###