"""Blob storage for uploaded documents.

Keys are generated by the server (`new_storage_key`), never derived from a user's filename.
"""

import asyncio
import re
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Protocol

from app.core.config import get_settings

_KEY_RE = re.compile(r"^[a-f0-9]{32}(/[a-f0-9]{32})?$")


class StorageError(Exception):
    pass


class Storage(Protocol):
    async def save(self, key: str, data: bytes) -> None: ...

    async def read(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...


def new_storage_key(workspace_id: uuid.UUID) -> str:
    """Random, opaque key namespaced by workspace: `<workspace hex>/<random hex>`."""
    return f"{workspace_id.hex}/{uuid.uuid4().hex}"


class LocalStorage:
    """Stores files on local disk under `root`. For development and tests."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        # Keys are server-generated, but refuse anything that could escape the root.
        if not _KEY_RE.match(key):
            raise StorageError("Invalid storage key")
        return self.root / key

    async def save(self, key: str, data: bytes) -> None:
        path = self._path(key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

        await asyncio.to_thread(_write)

    async def read(self, key: str) -> bytes:
        path = self._path(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except FileNotFoundError as exc:
            raise StorageError("Stored file not found") from exc

    async def delete(self, key: str) -> None:
        await asyncio.to_thread(self._path(key).unlink, missing_ok=True)


@lru_cache
def get_storage() -> Storage:
    settings = get_settings()
    if settings.storage_backend == "local":
        return LocalStorage(settings.local_storage_dir)
    # Seam for production: add a GCSStorage implementing the Storage protocol and
    # select it here with STORAGE_BACKEND=gcs.
    raise ValueError(f"Unsupported STORAGE_BACKEND: {settings.storage_backend}")
